name: Run Unit Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: "postgresql://docker:docker@localhost:5432/apisolid"

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Set Prisma Schema Path
        run: echo "PRISMA_SCHEMA_PATH=$(pwd)/prisma/schema.prisma" >> $GITHUB_ENV

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Run Prisma Migrations
        run: npx prisma migrate deploy

      - name: Run Vitest
        run: npm run test